# Generated by Django 4.0.4 on 2022-05-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=256)),
                ('comment', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
    ]
