# Generated by Django 4.0.4 on 2022-05-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('explanation', models.CharField(default='', max_length=256)),
            ],
            options={
                'db_table': 'Categorys',
            },
        ),
        migrations.RenameModel(
            old_name='ArticleModel',
            new_name='Article',
        ),
    ]
